### ISSUE TITLE
No way to set custom ParamBuilders

### ISSUE THREAD

**Issue by rrenomeron** [Unicon/shib-cas-authn3#12]
It looks like the mechanism from the v2 CasLoginHandler for adding custom IParameterBuilders to add additional parameters to the CAS login URL was not ported to the v3 plugin.

**Comment by jtgasper3** [comment]
Yeah, it looks like a way to add in additional ones was left out during the code migration from v2 to v3.

If you do not mind me asking. What is your use case? I've not actually seen anyone use a custom impl.

**Comment by rrenomeron** [comment]
I have made some customizations to CAS that allow an application to force a
particular authentication method by adding a parameter to the login URL.
It's meant to mimic the proposals around authentication LOA that were
floating around in the old Jasig wiki.

I've written the code for it, but am busy messing with getting a working
IdP v3 instance up, so I haven't had a chance to test it yet.

**Comment by mmoayyed** [comment]
This is done.
