### ISSUE TITLE
README.md has incorrect config in comments

### ISSUE THREAD

**Issue by nombab** [Unicon/shib-cas-authn3#13]
Line 

"Set the idp.authn.flows to ShibCas. Or, for advance cases, add ShibCas to the list."

should say

Set the idp.authn.flows to Shibcas. Or, for advance cases, add Shibcas to the list.

**Comment by mmoayyed** [comment]
Great. Could I ask you to submit a PR to fix this?

**Comment by jtgasper3** [comment]
Thanks @n99. I've fixed that issue.
