### ISSUE TITLE
Back button and Error processing ShibCas authentication request

### ISSUE THREAD

**Issue by khsitdev** [Unicon/shib-cas-authn3#15]
I visit a protected page on an SP, get redirected to Shib, sent to CAS via shib-cas-authn3, log in, eventually get sent back to SP, get page. Great! Then I hit the back button.

On some browsers, I get a 500 exception "Error processing ShibCas authentication request", with root cause "No conversation state found in session for key (e1s1)". Exception at end of this issue. I'm running Tomcat on the IdP (for now).
The URL at this point is /idp/Authn/ExtCas?conversation=e1s1&ticket=ST-blah-blah-casa
It seems to happen on:
Edge on Windows 10.
Chrome in Windows 10.
Safari on Mac.
Chrome on Mac.
Opera on Mac.

In some browsers, I don't get the exception, I get directed to /idp/profile/SAML2/Redirect/SSO, which shows me a Shibboleth "Stale Request" message, which is nice.
This happens on:
IE 11 on Windows 10. But if I hit the back button again, I get the exception.
Firefox on Windows 10. Hitting the back button again remains on the page, which is very nice.
Firefox on Mac. Hitting the back button again remains on the page, which is very nice.

Anyway, is this expected, is Firefox doing something that the others aren't, am I missing something completely, or could you suggest any way I can avoid ever seeing the exception?

Thanks,
Kevin

---

HTTP Status 500 - Error processing ShibCas authentication request

type Exception report

message Error processing ShibCas authentication request

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Error processing ShibCas authentication request
    net.unicon.idp.externalauth.ShibcasAuthServlet.doGet(ShibcasAuthServlet.java:152)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    net.shibboleth.idp.log.SLF4JMDCServletFilter.doFilter(SLF4JMDCServletFilter.java:72)
    net.shibboleth.utilities.java.support.net.RequestResponseContextFilter.doFilter(RequestResponseContextFilter.java:60)
    org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
root cause

net.shibboleth.idp.authn.ExternalAuthenticationException: No conversation state found in session for key (e1s1)
    net.shibboleth.idp.authn.ExternalAuthentication.startExternalAuthentication(ExternalAuthentication.java:132)
    net.unicon.idp.externalauth.ShibcasAuthServlet.doGet(ShibcasAuthServlet.java:113)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    net.shibboleth.idp.log.SLF4JMDCServletFilter.doFilter(SLF4JMDCServletFilter.java:72)
    net.shibboleth.utilities.java.support.net.RequestResponseContextFilter.doFilter(RequestResponseContextFilter.java:60)
    org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.54 logs.

Apache Tomcat/7.0.54

**Comment by ghost** [comment]
We saw these errors crop as well after deploying our Shibboleth upgrade to use the plugin.  Along with use of the back button or bookmarked links, we are seeing issues because of our HA setup and the use of a load balancer.  If a user sits on the login page for a duration that is longer than the sticky session assignment by the load balancer this error will happen if they are dispatched to a different server than the one that handled their original request.

Would it be possible to change the plugin to hold the conversation state in the client side storage, or is that not an option for this functionality?

**Comment by mmoayyed** [comment]
That's not about this plugin. The shib idp keeps is SWF state in memory server-side as does SWF in general. That needs to change over there for client-side storage; not something for this plugin to handle.

**Comment by ghost** [comment]
Got it.  Thanks for the response.  Looks like 3.3.0 of the IdP may have some changes to handle this situation at least more gracefully.

> ```
> Improvements in back-button behavior result in some new exception types being raised. Mapping them to existing back-button behavior requires additions to one of the earlier message property files:
> NoSuchFlowExecutionException = stale
> ExternalAuthenticationException = stale
> ```

**Comment by jtgasper3** [comment]
I'm going to close this. There was some changes made to the plugin to help with this. Unfortunately, 3.3.0's `NoSuchFlowExecutionException` didn't really help much in this case... at least I couldn't get it to invoke naturally.
