### ISSUE TITLE
Does Shibcas require any extra configuration on CAS 4 side?

### ISSUE THREAD

**Issue by jeffmc930** [Unicon/shib-cas-authn3#17]
While I see the URL contains the entityId for the SP, I'm not seeing it show up in the logs on the CAS side. Is there any extra config that needs to be done on CAS 4 to utilize the entityId being passed to it? 

We added:
<init-param>
        <param-name>parametersToCheck</param-name>
        <param-value>entityId ticket SAMLArt service renew gateway warn logoutUrl pgtUrl</param-value>
      </init-param>

but don't see the entityId show up as part of the org.jasig.cas.web.support.CasArgumentExtractor log entries. The extractor does show the IDP "service" parameter including the trailing conversation parameter from the login URL, but not the entityID. It's potentially be properly extracted and used somehow, but I'm not seeing it.

**Comment by mmoayyed** [comment]
What do you need to do with the entityID?

**Comment by jeffmc930** [comment]
Use it for authN (2FA) eventually and authZ (blocking users that don't have a required affiliation) so it is consistent experience for all apps.

**Comment by mapgrady** [comment]
The original idea for passing it along to CAS was so that one could tailor the CAS login page to the SP, or as noted, decide you needed 2FA etc. So it does need to be made available.

**Comment by jtgasper3** [comment]
@jeffmc930, CAS Server does not do anything with the passed along entityID. That code/logic needs to be implemented per the needs of the adopter.

**Comment by mmoayyed** [comment]
@jeffmc930 what you describe isn't implemented. Entity ID is only processed by CAS practically today to display SAML MDUI on the login page, ,but there isn't much else you can do Out-of-the-box with CAS unless of course you code the rest. If you'd like, you are welcome to submit an issue to the project detailing that use case so it can tracked to find a sponsor.

**Comment by jeffmc930** [comment]
Fair enough. It looks like we need to utilize Unicon to add this functionality to the MFA/Duo and Pac4J (we are using it for delegated auth). Do have a sense how much work that might be, so I can let Jeremy know?

**Comment by mmoayyed** [comment]
Without knowing all the details, I would speculate something like 60 hrs [or more] but it would be safer for Jeremy and David Lipari @ Unicon to talk and schedule a call so we all can discuss and review exactness of the requirements.

**Comment by jeffmc930** [comment]
Okay. Thanks.

**Comment by jeffmc930** [comment]
We are now on CAS 5, and realize this issue must have never been included in all the custom work we had completed via Unicon. Is there any chance that CAS 5 is any closer than CAS 4 was to supporting use of the appended or embedded URLs?

Jeff

**Comment by jtgasper3** [comment]
Hi Jeff,

Thought I'd follow-up on this. CAS Server 5.2.0 should have support for the appended entityId. Please see https://apereo.github.io/cas/development/integration/Shibboleth.html#relying-party-entityid
 and https://apereo.github.io/cas/development/installation/Configuring-Multifactor-Authentication-Triggers.html#entity-id-request-parameter.

As for the embedded entityId route I just pushed a beta of the fix of the issue https://github.com/Unicon/shib-cas-authn3/issues/26#issuecomment-328214366

**Comment by jeffmc930** [comment]
Hi John,

Following up on this. Before I started to test, I saw that someone else had tested and found issues. Will you have anytime again soonish to look at this issue? Do you need any further info?

Thanks,
Jeff
