### ISSUE TITLE
LOGOUT

### ISSUE THREAD

**Issue by cronzero** [Unicon/shib-cas-authn3#19]
Hi.
Should the logout on CAS work correctly?
After login, when i hit logout on application it ends up on shibboleth logout page, but it keeps me login on CAS.
No error in logs. Can this be wrong configuration ?

**Comment by mmoayyed** [comment]
You have a few options. here are my favorites:
1. Let the application go to /cas/logout instead.
2. Mod your idp to redirect logout to /cas/logout
