### ISSUE TITLE
Sample attribute-resolver.xml

### ISSUE THREAD

**Issue by lchanouha** [Unicon/shib-cas-authn3#23]
Hello,
I can"t get my CAS 2.0 attributes propagated to Shibboleth (only uid)
Could you send a working attribute-resolver.xml file for example ? I guess i shall use a DataConnector..

Thank you

**Comment by mmoayyed** [comment]
There is no such sample. The attributes are put into external authN under `ExternalAuthentication.SUBJECT_KEY`
Write a data connector that knows how to extract them. The Shibboleth project may be able to provide better samples and walkthroughs.
