### ISSUE TITLE
Embed Service when an entityId contains a "?"

### ISSUE THREAD

**Issue by jschrad4** [Unicon/shib-cas-authn3#32]
I have a service that has specified an entityId like so:
https://test.edu/sp?alias=1234-1234-1234-1234

An entityId containing a "?" appears to suffer from the "Original service xyz and the supplied service do not match" issue.

**Comment by mmoayyed** [comment]
@jschrad4 Do you have an update on the status of the proposed patch? Can we close this issue by merging the patch for the CAS client?

**Comment by mmoayyed** [comment]
Fixed via https://github.com/apereo/java-cas-client/pull/231 Will be included here once it's released properly.
