### ISSUE TITLE
Example CAS Service Entries not working

### ISSUE THREAD

**Issue by ajb2** [Unicon/shib-cas-authn3#33]
I am using shibcas.entityidlocation = embed on 3.2.3 and using the example in the documentation of a CAS serviceID, CAS does not load the service.

Using this example:

https://shibserver.example.edu/idp/Authn/ExtCas\?conversation=[a-z0-9]*&entityId=http://testsp.school.edu/sp

In the CAS log, it is rejecting the service file that I created with this error:

2018-02-07 11:51:58,207 ERROR [org.apereo.cas.services.AbstractResourceBasedServiceRegistryDao] - <Error reading configuration file [SRVC1-10000007.json]>
java.lang.IllegalArgumentException: org.hjson.ParseException: Expected valid escape sequence at 3:54

My service file is:

{
  "@class" : "org.apereo.cas.services.RegexRegisteredService",
  "serviceId" : "https://idp.myu.edu/idp/Authn/ExtCas\?conversation=[a-z0-9]*&entityId=https://sso.srvc1.com/sp/shibboleth",
  "name" : "SRVC1",
  "id" : 10000007,
  "description" : "SRVC1 Login",
  "evaluationOrder" : 1
}

Thanks.
Al

**Comment by mmoayyed** [comment]
This is not an issue with `shib-cas-authn3`. It's an issue with your CAS server deployment.

**Comment by ajb2** [comment]
So is the example in the documentation correct then?
