### ISSUE TITLE
Can't rebuild war in Shibboleth 3.4.3 for ShibCas

### ISSUE THREAD

**Issue by vwbusguy** [Unicon/shib-cas-authn3#39]
We are currently using shib-cas-authn3 with version 3.3.2 and are trying to upgrade to Shibboleth 3.4.3.  In both cases, we are using shib-cas-authn version 3.2.3 and in both cases we are using the [Unicon Shibboleth docker image](https://github.com/Unicon/shibboleth-idp-dockerized).  I'm happy to file this in that repo if it is more appropriate.  

We created a script to inject the shibcas configuration in during the docker build:
```
#!/usr/bin/env python

import subprocess,re,os

idp_home = "/opt/shibboleth-idp/"
prod_web_xml = idp_home + "webapp/WEB-INF/web.xml"
web_str = ""
shibcas_reg = re.compile(r'<servlet(\-mapping)?>\n.*ShibCas.*\n.*(\n.*)?\s+</servlet(\-mapping)?>')

print "Rebuilding war for ShibCas support."
subprocess.call([idp_home + "bin/build.sh", "-Didp.target.dir=" + idp_home])

with open(prod_web_xml,'r') as xml_f:
        xml_str = xml_f.read()
        web_str = shibcas_reg.sub('',xml_str)

with open(prod_web_xml,'w') as xml_f:
        xml_f.write(web_str)
```
This works fine in 3.3.x, but in 3.4.x, this fails with:
`/opt/shibboleth-idp/bin/build.xml:564: /opt/shibboleth-idp/dist/webapp does not exist.`

I've been searching the github issue and mailing lists but haven't as of yet found a way to get this to work.  I'm otherwise able to build the image without including this step for shib-cas-authn.  Is there something I'm missing in order to make shib-cas-authn3 compatible with shibboleth-idp 3.4.3?

**Comment by jtgasper3** [comment]
Yeah, the war doesn't need to be rebuilt in the Docker image. Just overlay your files into `/opt/shibboleth-idp/webapp/`, which is an exploded war. Rebuilding (the war) does absolutely nothing in a containerized world other than waste diskspace and burn CPU time causing our Earth to heat up un-necessarily.

**Comment by vwbusguy** [comment]
Thanks - I'll test it out without rebuilding the war file.

**Comment by vwbusguy** [comment]
It looks like skipping the build.sh seems to work.  Many thanks, @jtgasper3 .
