### ISSUE TITLE
No bean named 'shibboleth.authn.External.populat eUIInfo' is defined

### ISSUE THREAD

**Issue by salaun-urennes1** [Unicon/shib-cas-authn3#6]
Hello,

First of all, thanks for developing this useful authentication plugin for the 3.x Shibboleth IdP.

I've followed your documentation and installed the shib-cas-authn3-3.0.0 with a Shibboleth IdP 3.1.1.

I then got the following error while initiating a login session:
2015-06-02 09:38:29,972 - ERROR [net.shibboleth.idp.authn:-2] - Uncaught runtime exception
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'SetRPUIInformation' defined in file [/opt/shibboleth-idp3/flows/authn/Shibcas/shibcas-authn-beans.xml]: Cannot resolve reference to bean 'shibboleth.authn.External.populateUIInfo' while setting bean property 'activationCondition'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'shibboleth.authn.External.populateUIInfo' is defined at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'shibboleth.authn.External.populateUIInfo' is defined at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:687)

I had to change the flows/authn/Shibcas/shibcas-authn-beans.xml file as follows:

---

**\* 23,29 ****

```
  <bean id="SetRPUIInformation"
        class="net.shibboleth.idp.ui.impl.SetRPUIInformation" scope="prototype"
```

!           p:activationCondition-ref="shibboleth.authn.External.populateUIInfo"
            p:httpServletRequest-ref="shibboleth.HttpServletRequest">
          <property name="fallbackLanguages">
              <bean parent="shibboleth.CommaDelimStringArray" c:_0="%{idp.ui.fallbackLanguages:}" />
--- 23,29 ----

```
  <bean id="SetRPUIInformation"
        class="net.shibboleth.idp.ui.impl.SetRPUIInformation" scope="prototype"
```

!           p:activationCondition-ref="shibboleth.authn.Cas.populateUIInfo"
            p:httpServletRequest-ref="shibboleth.HttpServletRequest">
          <property name="fallbackLanguages">
              <bean parent="shibboleth.CommaDelimStringArray" c:_0="%{idp.ui.fallbackLanguages:}" />

---

**\* 33,39 ****
      <bean id="ValidateExternalAuthentication"
            class="net.shibboleth.idp.authn.impl.ValidateExternalAuthentication" scope="prototype"
            p:classifiedMessages-ref="shibboleth.authn.Cas.ClassifiedMessageMap"
!           p:resultCachingPredicate="#{getObject('shibboleth.authn.External.resultCachingPredicate')}" />

```
  <util:constant id="shibboleth.authn.Cas.populateUIInfo" static-field="java.lang.Boolean.FALSE" />
```

--- 33,39 ----
      <bean id="ValidateExternalAuthentication"
            class="net.shibboleth.idp.authn.impl.ValidateExternalAuthentication" scope="prototype"
            p:classifiedMessages-ref="shibboleth.authn.Cas.ClassifiedMessageMap"
!           p:resultCachingPredicate="#{getObject('shibboleth.authn.Cas.resultCachingPredicate')}" />

```
  <util:constant id="shibboleth.authn.Cas.populateUIInfo" static-field="java.lang.Boolean.FALSE" />
```

Maybe that bean definition should be changed on your end too?

Regards.

**Comment by jtgasper3** [comment]
Thanks for letting me know about this. I thought I had already fixed this. I wonder if I have an outstanding push sitting around somewhere.

**Comment by jtgasper3** [comment]
So I looked through the code again... Assuming I'm reading the diff that you posted properly, these have already been fixed. When did you pull this code?

Both of these should have been fixed in April?
https://github.com/Unicon/shib-cas-authn3/blob/master/IDP_HOME/flows/authn/Shibcas/shibcas-authn-beans.xml#L26 
https://github.com/Unicon/shib-cas-authn3/blob/master/IDP_HOME/flows/authn/Shibcas/shibcas-authn-beans.xml#L36

Please let me know if I'm not following correctly.

**Comment by salaun-urennes1** [comment]
Hi John,

I downloaded the 3.0.0 version.
I should have git-cloned the master...

Thanks for the quick feedback.

Le 02/06/2015 18:49, John Gasper a écrit :

> So I looked through the code again... Assuming I'm reading the diff 
> that you posted properly, these have already been fixed. When did you 
> pull this code?
> 
> Both of these should have been fixed in April?
> https://github.com/Unicon/shib-cas-authn3/blob/master/IDP_HOME/flows/authn/Shibcas/shibcas-authn-beans.xml#L26 
> 
> https://github.com/Unicon/shib-cas-authn3/blob/master/IDP_HOME/flows/authn/Shibcas/shibcas-authn-beans.xml#L36
> 
> Please let me know if I'm not following correctly.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Unicon/shib-cas-authn3/issues/6#issuecomment-108012443.

## 

_Olivier Salaün_
Etudes et projets applicatifs
Tél : +33 2 23 23 71 27
Fax : +33 2 23 23 71 11
www.renater.fr http://www.renater.fr
    RENATER
263 Avenue du Gal Leclerc
35042 Rennes Cedex
