### ISSUE TITLE
Resolver definitions from CAS

### ISSUE THREAD

**Issue by AshMartian** [Unicon/shib-cas-authn3#8]
Hello,

I am currently using shib-cas-authn3 to successfully authenticate Shib through my CAS server. I am trying to write my attribute-resolver.xml file for use with a vendor. I need to access the user fields defined in my CAS deployerConfigContext.xml. However I can only figure out how to get the PrincipalName. Is it possible to see all the information provided by CAS in a resolver? Or do I have to take the PrincipalName and search LDAP for the fields I need?

**Comment by mmoayyed** [comment]
This is presently not possible. You can only get back from the principal from CAS. Attributes that are going back to the SP must be resolved and released by the idp.

**Comment by AshMartian** [comment]
Okay, thank you for the information. I will use LDAP to pull the information I need.
